In [ ]:
#At the core of numpy is nd array object.
#array >> basic data structure of numpy
#if we have all the data structure in python then why array

In [ ]:
#numpy array vs python dtaa structures (list, tuple, sets)
#list stores the data with reference address >> make list slow
#in general as well Python is slow
#till 2008-09 all the data science was done in R and matlab
#some scientist says that why not develop a data structure in C, and use in Python>> Numpy array comes into the picture

In [ ]:
#numpy>> numerical Python >> library (multiple modules and packages)
#2005 by Travis Oliphant

In [8]:
import numpy as np

In [10]:
np.__version__

'1.26.4'

In [12]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [14]:
#Numpy stores data in an array
#An array is container to store the data of same datatype
#comutation with numpy array is fast
#mathematical computation

In [18]:
l = [1, 2, 3, 4, 5]
np.array(l)

array([1, 2, 3, 4, 5])

In [20]:
a = np.array(l)
type(a)

numpy.ndarray

In [ ]:
#numpy memory use is lesser than list

In [22]:
a = np.arange(1000000)
a

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [32]:
b = list(range(1000000))
type(b)

list

In [34]:
import sys

In [36]:
sys.getsizeof(a)

4000112

In [38]:
sys.getsizeof(b)

8000056

In [42]:
#list memory is twice that of array >> why less memory?
#Array unlike list as contiguous memory allocation


In [46]:
#can we reduce the array memory more?


a = np.arange(1000000, dtype=np.int16)
sys.getsizeof(a)

2000112

In [48]:
#can we reduce the array memory more?


a = np.arange(1000000, dtype=np.int8)
sys.getsizeof(a)

1000112

In [66]:
#numpy array is faster?


#using list
import time
start = time.time()


a = list(range(10000000))
b = list(range(10000000, 20000000))

c = []
for i in range(len(b)):
    res = a[i]+b[i]
    c.append(res)

end = time.time()

print("The execution time is:", end-start)

The execution time is: 4.020251989364624


In [68]:
#using numpy array

import time
start = time.time()


a = np.arange(10000000)
b =np.arange(10000000, 20000000)

c = a+b
end = time.time()

print("The execution time is:", end-start)

The execution time is: 0.4360682964324951


In [70]:
#numpy array creating

#numpy array will always be homogenous

np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [74]:
np.array([1, 2, 3.4])

array([1. , 2. , 3.4])

In [72]:
np.array([1, 2,3, "Ajay"])

array(['1', '2', '3', 'Ajay'], dtype='<U11')

In [76]:
#1-d array
a = np.array([1, 2, 3, 4])

In [78]:
a

array([1, 2, 3, 4])

In [80]:
#visualisation >> 1d array is vector

In [87]:
#2d dimensional array>> matrix
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
#3dimensional array >> tensor
np.array([[[1,2,3], [4, 5, 6], [7, 8, 9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
#3dimensional array is made up of 2 dimensional array, 2d array is made up of 1 d array

In [91]:
#asarray
np.asarray([1, 2, 3])

array([1, 2, 3])

In [93]:
#asanyarray #converts the input to an nd array but leave array and its sub class(matrix) as it is, example: np.matrix
np.asanyarray([1, 2,3])

array([1, 2, 3])

In [99]:
a = np.matrix([1, 2, 3, 4])#matrix is a specialised array, 2 dimensional
a

matrix([[1, 2, 3, 4]])

In [101]:
np.asanyarray(a)

matrix([[1, 2, 3, 4]])

In [103]:
#can we make 3 dimensional matrix? 2d
a = np.matrix([[[1, 2, 3, 4]]])

ValueError: matrix must be 2-dimensional

In [105]:
#creating array from tuples
t = ([1, 2, 3], [4, 5, 6])
type(t)

tuple

In [107]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
#from set
a = (1, 2, 3)
np.array(a)

array([1, 2, 3])

In [109]:
#creating array from function
np.fromfunction(lambda i, j: i==j, (3,3)) #construct an array by executing a function over each coordinate

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [123]:
a = np.fromfunction(lambda i, j: i==j, (3,3))
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [125]:
a.astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#internal assignment, use np.fromfunction other than lambda function

In [117]:
np.fromfunction(lambda i, j: j, (2, 2), dtype=float)

array([[0., 1.],
       [0., 1.]])

In [127]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [129]:
np.fromstring("12 13 14", sep = " ") #values inside string should be numerical

array([12., 13., 14.])

In [141]:
np.fromstring("12,13,14", sep = ",")

array([12., 13., 14.])

In [160]:
#for string character you have  to use split
string = 'Ajay,Bijay,Sanjay'
string1 = string.split(',')
np.array(string1)

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [137]:
iterable = (i for i in range(5))
iterable

<generator object <genexpr> at 0x00000227C7777100>

In [139]:
np.fromiter(iterable, int)

array([0, 1, 2, 3, 4])

In [153]:
#arange >> similar to range, in numpy we have range
list(range(10)) #in range, you need to convert or type caste to any data structure

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [156]:
np.arange(1, 10, 0.2) #to generate a sequence of no
#give me numbers evenly spaced between 1 and 10 with a space of 0.2

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [158]:
np.linspace(1, 5, 10)
#give me 10 numbers evenly spaced between 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [162]:
#using np.ones 2-d array
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [166]:
np.ones(3) #1d array

array([1., 1., 1.])

In [171]:
#all elements are zero
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [195]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [197]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [199]:
np.two((2, 3)) #you can not have np.twos

AttributeError: module 'numpy' has no attribute 'two'

In [173]:
#identatity>> 2d matris or 2 d array where diagonal elements are 1
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [293]:
np.eye(3) #return a 2 d array with ones on the diagonal element

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [295]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [297]:
np.empty((3, 4)) #Return a new array of given shape and type, without initializing entries.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [209]:
#zeros, ones in n dimension
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [221]:
a = np.ones((1, 3, 4)) # 3 rows 4 columns in the third dimension
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [225]:
a.ndim

3

In [215]:
np.zeros((1, 3, 2)) #3 rows 2 columns in the third dimension

array([[[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [227]:
np.zeros((2, 3, 2)) #3 rows 2 columns repeated two times to create third dimension
#it proved 3d is made up of 2e, 2d is made up of 1d

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [231]:
b = np.zeros((1, 2, 3, 2))
b

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [233]:
b.ndim

4

In [235]:
np.zeros((2, 5, 3, 2)) #3 rows 2 columns repeat 5 times for third dimension and repeat two times for 4th dimension

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [177]:
#creating on numpy array using reshape
#reshape again in the class ahead
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
##attributes of array

In [179]:

a  = np.array([1, 2, 3])
a

array([1, 2, 3])

In [181]:
a.shape

(3,)

In [183]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b.shape

(2, 3)

In [185]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
b.ndim

2

In [189]:
b.size

6

In [191]:
b.itemsize # length of one array element in bytes.

4

In [193]:
b.dtype

dtype('int32')

In [239]:
#changing the datatype
b.astype(np.int16)

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]], dtype=int16)

In [246]:
#array operations
#reshape of array

In [256]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [258]:
a.shape

(4, 3)

In [260]:
a.size

12

In [262]:
a.ndim

2

In [266]:
a.reshape(2, 6)
#you can provide the dimension of array in the reshape only if the product is equal to size of the matrix
#because you dont want to loose the data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [268]:
a.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [270]:
a.reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [274]:
a.reshape(5, 2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [278]:
#if you dont know what would be the rows and columns>> just put any negative value
a.reshape(3, -2)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [280]:
a.reshape(-100, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [409]:
#other ways of reshaping
a #this is a matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [411]:
np.transpose(a)

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [413]:
a.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [415]:
a.ravel() #reduce any dimension array to one dimension

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [419]:
a.flatten() #return a copy of the array collapsed into one dimesnion

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [421]:
#expand dimension
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [423]:
arr.ndim

1

In [427]:
np.expand_dims(arr, axis=0) #increase the dimension by 1 in provided axis

array([[1, 2, 3, 4]])

In [429]:
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [431]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [433]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [435]:
np.expand_dims(a, axis=0) 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [439]:
np.expand_dims(a, axis=1)  #row wise dimension has been increased

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [449]:
b = np.squeeze(a) #Remove axes of length one from `a`

In [451]:
np.squeeze(b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [455]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [453]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6,
       6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9])

In [457]:
np.repeat(a, 2, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

In [459]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [465]:
np.roll(a, -1) #one lement shifted

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [467]:
np.roll(a, -2) #two element shifted

array([[3, 4, 5],
       [6, 7, 8],
       [9, 1, 2]])

In [469]:
c = np.array([[1,2], [3, 4], [5,6], [7,8]])
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [473]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [475]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [477]:
#stacking

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [479]:
b = np.array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [487]:
#horizontal, vertical


In [489]:
np.hstack((a, b)) #side by side

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [491]:
np.vstack((a, b)) #top to top stacking

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
#splitting >> always split will be equal

In [499]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [495]:
np.hsplit(a, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [497]:
np.vsplit(a, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [501]:
np.hsplit(a, 4)

ValueError: array split does not result in an equal division

In [503]:
z = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [5, 6, 7, 8]])
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [509]:
np.vsplit(z, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]

In [511]:
np.vsplit(z, 3)

ValueError: array split does not result in an equal division

In [483]:
#arithmatic operation
#scalar operation

In [485]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [287]:
a+5


array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [289]:
a*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [291]:
a-1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [301]:
#comparison
a == 2

array([[False,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [303]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [307]:
 a ** a

array([[         1,          4,         27],
       [       256,       3125,      46656],
       [    823543,   16777216,  387420489],
       [1410065408, 1843829075, -251658240]])

In [309]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5],
       [5. , 5.5, 6. ]])

In [311]:
a // 2

array([[0, 1, 1],
       [2, 2, 3],
       [3, 4, 4],
       [5, 5, 6]], dtype=int32)

In [313]:
p = np.array([2.3, 4.2, 6.1])
np.round(p)

array([2., 4., 6.])

In [345]:
sum(a) #using python's sum

array([22, 26, 30])

In [335]:
np.sum(a) #using numpy sum

78

In [347]:
np.sum(a, axis=0) #in case of array axis=0 means column wise

array([22, 26, 30])

In [349]:
np.sum(a, axis=1)

array([ 6, 15, 24, 33])

In [337]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [339]:
np.max(a)

12

In [341]:
np.min(a)

1

In [357]:
np.min(a, axis=0)

array([1, 2, 3])

In [353]:
np.prod(a)

479001600

In [355]:
np.prod(a, axis=1)

array([   6,  120,  504, 1320])

In [359]:
#statistical calculation

In [365]:
np.var(a)

11.916666666666666

In [367]:
np.var(a, axis=0)

array([11.25, 11.25, 11.25])

In [369]:
np.var(a, axis=1)

array([0.66666667, 0.66666667, 0.66666667, 0.66666667])

In [371]:
np.mean(a)

6.5

In [373]:
np.mean(a, axis=0)

array([5.5, 6.5, 7.5])

In [375]:
np.median(a)

6.5

In [377]:
np.std(a)

3.452052529534663

In [379]:
np.std(a, axis=0)

array([3.35410197, 3.35410197, 3.35410197])

In [381]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [385]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [387]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665]])

In [389]:
#trigonometric 
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])

In [391]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396]])

In [393]:
np.tan(a)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01],
       [ 8.71447983e-01, -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01]])

In [405]:
p

array([2.3, 4.2, 6.1])

In [399]:
#ceil
np.ceil(p)

array([3., 5., 7.])

In [401]:
np.floor(p)

array([2., 4., 6.])

In [407]:
np.round(p)

array([2., 4., 6.])

In [513]:
p

array([2.3, 4.2, 6.1])

In [ ]:
#interview questions
#why numpy array is faster?
#what is use ravel?, what is expand_dims?
#how to do arithmatic operations?